eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    fetch-registry: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

